services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: scm
      MYSQL_USER: root 
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "16.16.24.173:3306", "-uroot", "-padmin"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmydmin_con
    ports:
     - "8081:80"
    environment: 
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: admin
    depends_on:
      - mysql_db

  springboot:
    build: .
    container_name: scm_springboot_project
    environment:
      SERVER_PORT: 8080
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: scm
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
    ports:
      - "8082:8080"
    depends_on:
      mysql_db:
        condition: service_healthy
volumes:
  mysql_data:
